linters-settings:
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/coronon/go-storage

  gocritic:
    # Which checks should be enabled; can't be combined with 'disabled-checks';
    # See https://go-critic.github.io/overview#checks-overview
    # To check which checks are enabled run `GL_DEBUG=gocritic golangci-lint run`
    # By default list of stable checks is used.
    # enabled-checks:
    #   - rangeValCopy
    # Which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - ifElseChain
      - elseif

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - contextcheck
        - goconst
        - gosec
        - noctx

linters:
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - mnd
    - nilerr
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - usetesting
    - wastedassign
    - whitespace
