name: CI

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64

  mod-tidy:
    name: Go Mod Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Tidy
        run: |
          cp go.sum go.sum.old
          go mod tidy
          diff go.sum.old go.sum

  test:
    name: Go ${{ matrix.go-version }} test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version:
          - stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup cloud credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Test
        run: go test -v -race ./...
        env:
          GOOGLE_CLOUDSTORAGE_TEST_BUCKET: ${{ secrets.GOOGLE_CLOUDSTORAGE_TEST_BUCKET }}
